### ISSUE TITLE
关于发送和接收图片的问题

### ISSUE THREAD

**Issue by ganghui22** [wechaty/dotnet-wechaty#33]
我最近想用.NET Wechaty 来发送和接收图片，但是一直没有调通程序。
#### 这是我在OnMessage里写的接收图片的代码，
```csharp
private async void OnMessage(Message message)
        {
            _logger.LogInformation($"wechat receive message (Age={message.Age}): {message.Text}");
            if (string.IsNullOrEmpty(message.Room?.Id) && !string.IsNullOrEmpty(message.From?.Id))
            {                  
                string message_type = message.Type.ToString();
                _logger.LogInformation($"message_type:{message_type}");
                var message_file = await message.ToFileBox();
                string name = message_file.Name;
                await message_file.ToFile(name); 
                _logger.LogInformation($"message_type:{message_type}\r\nmessage_file_name:{name}");
            }
        }
```
但是报这个错误,
```log
info: RobotDemo.Server.Services.WechatService[0]
      message_type:Image
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'value')
   at Newtonsoft.Json.Linq.JToken.EnsureValue(JToken value)
   at Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value)
   at Wechaty.Module.Filebox.FileBox.FromJson(String fileboxStr)
   at Wechaty.Module.PuppetService.GrpcPuppet.MessageFile(String messageId)
   at RobotDemo.Server.Services.WechatService.OnMessage(Message message) in /home/xdy/workspace/robotdemo/RobotDemo/Server/Services/WechatService.cs:line 109
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```
#### 这是我发送图片的代码
```csharp
public async Task<TalkResult> SayImage(object context, string to,string path)
        { 
             var contact = await _bot.Contact.Find(new ContactQueryFilter { Name = to });
            if (contact != null)
            {
                _logger.LogInformation($"Found contact: {contact.Name}, send an image to him/her");
                
                FileBox filebox_before = FileBox.FromFile(path);
                string base64 = await filebox_before.ToBase64();
                FileBox  filebox_After = FileBox.FromBase64(base64, path);
                FileBoxJsonObject jsonText = filebox_After.ToJson();
                FileBox fileBox = FileBox.FromJson(jsonText);
                try{
                    var result = await contact.Say(fileBox2);
                }
                catch(Exception ex)
                {
                    _logger.LogError(ex,$"Send a file failed!\n Error:{ex.Message}");
                }
                
                return new TalkResult() { Success = true };
            }
            else
            {
                _logger.LogWarning($"Contact {to} NOT found!");
                return new TalkResult() { Success = false, ErrorMessage = $"找不到{to}" };
            }
        }
```
报这个错误,
```log
Grpc.Core.RpcException: Status(StatusCode="Unknown", Detail="Error: unknown filebox json object{type}: {"boxType":1,"base64":"iVBORw0KGgoAAAANSUhEUgAAAjIAAAEyCAAAAADFT2UYAAATv0lEQVR4Ae3Bz4r03XoQ0PXcg5BZPATMICGcwX5E1EgGgpNETtB7CMkdiOGITsRJIDPnGehEJBEVIhkoRBHy7HBECThQcjKTXMS2uqqru6rrT9evu/qrer/aa0WZpiWiTNMSUaZpiSjTtESUaVoiyjQtEWWalogyTUtEmaYlokzTElGmaYko07RElGlaIso0LRHlO5TK9I2Lcj2pnJWUj0llugdRriYpZyUjUBZJa2W6A1GuJpUz0pPRE+USaU+Z7kCUq0lDdyA9qfSkmkB5ldYqvaNMdyDK1TR0b6VXw0bPspXeMayFMt2BKFfT0L2VGALDiyhraa3Ss0oGoZp9oUx3IMrVNHRvJcNbUdLWcIlQpjsQ5WoaureS4a3g7/1z/OP/ZLhMKNMdiHI1Dd1byfBW1ywUynQHolxPozuQhisIZboDUa6moTuUwxWEMt2BKFfT6A6laj4vKNPtRbmaRncoDVcQlOn2omxk+ZykZHmW5VkariAo0+1F2cjRfUZ6q2yk4QpCme5AlGdN92HpiLKWDJ8XlOn2omxkNbqPSTsG4UlZS4bPC8p0e1G2GroPSS+qWQvKWjJcQSjT7UXZala6F2mlHJdOqGYtKGvJcAWhTLcX5UXzpNtIG2VfOmHQUzVrQVlLqvm8oEw3F+VFs9Y9SQw9vW/Y6qmajVDWfvsPVfN5QZluLsqLZqNbSQyEY4ajeqpmI5SNZPi8UKbbi7KredKRGFbCVjXv6KmajVA2kmo+LZTp9qLsatY6iWGhnqrZCOVZqubTQpluL8qzLDTPwsqwUE/VbITyLBk+LZTp9qI8y2o9h2c9rQzL9FQNHak8S6r5rFCm24uykQa9edYlhmV6+qWf+X//07Oykfyt/+qzgjLdXJSNNOzqiWGZnnaVjUQ1nxSU6eaiPMtqdvTEsFRY+6Wf+RdJefbbf6iaTwrKdHNRnqVhTzAs1a00K0F5lhg+KSjTzUXZSIY9wfBxQXmWqOZzgjLdXJRnadgTDJ8Qyov0g3/TfEpQppuL8iwNe4LhE0J5kfj5f6X5uKBMNxflWRr2BMMnhPIirf3qP2s+LJTp5qI8S8O+YPi4UHaltdJ8TCjTzUV5loZ9wfBxoexLG9V8RCjTzUXZymFfUDQfFMqBf/AXVoaPCGW6uShbOewLqvmwoBz6J/+R4SOCMt1alBfNvmD4uKAcSoYPCcp0a1F2NLuC4eOCcigZPiQo061F2dO8CoaPC8qBxPAxoUy3FuVFlpVmKxg+LigHEsPHBGW6sShbqVpH8ywYPi4ohxLDhwRlurEoW2mg02wEwyeEckQyfEhQphuL8iKr0TW9eRIMnxDKEcnwMaFMNxZlV7MjGD4hlCOS4WNCmW4syou0Mqx1WjB8QiiHEsPHhDLdWJSt9GRYC0YwfEIoh5Lhg0KZbizKVnoyrIWN4eNCOZQYPiaU6caibKVDwycE5VBaG5YLZbqxKFtpVzWfFZQj0sawUE9lurEoW8lwTUE5Im0MCwVlurEoW8lwTUE5oQXDQj2V6caibCXDNQXlhCYMS4Uy3ViUrWS4pqCc0IRhqaBMtxVlKxmuKpQTEsNSoUw3FmUrGa4qlGPSk2GxUKYbi7KVDFcVyhFpZfiAUKYbi/IiDVcVyqHf+FNU8wGhTDcW5UUariqUt/7RH+FXfqf5iFCmG4vyIg1XFZR9aaWajwllurEoL9JwVUHZ8xt/yq/8TvNBQZluK8qLVM01BWVPejEsF5TptqK8SIZrCsqu9KqaxYIy3VaUF8lwTUF5llTrVhph5Wf/bbNUKNN3qen2RXmRDFcVylZW86ynJ9UsFcr03Wg2un1RXiTDVYWylYZnPT0ZFgtl+mLNq+5AlBfJcFWhPEuGLq2UlTQsFpTpqzRH9FR2RHmVhqsKo3uWlFctDIsFZbq65rSeyo4or9JwVWF0x7UwLBaU6cqac3qWXVFepeGqQjmhBcNSQZmuptnRNUf0VHZEeZWGqwrKcS0YlgrK9HnNq47mpJ7Kjiiv0nBVweiOasGwVFCmz2gW6qnsiPIqGa4pGN1GKjtaMCwVlOlDmg8KZUeUV8lwTcHoNlLZ0YJhqVCm5ZpPCGVHlFfJcE3B6DZS2ZUMS4UyLdN8Uig7orxKhqsKo9tIyovWk2GpoEyXaa4jlB1RXiXDVYWhW0vKk2atp2GpoEzvaK4qlB1RXiXDVYWhW0sM9LQ1LBWU6aTmCwTlVZQdabiqMHRr6cCwWCjTcc2X6El5FWVHGq4qDN1a2jV8TCjTW811hbfKiyg70nBVYdA9SUao5lNCmV41VxPOKC+i7EjDVYWBjhYMnxbKtNJcRzAIO4Y3gvIiyo5kuKbevAjDp4Xy0Bq9+aSe1ayEHcMpQXkRZUcyXFNvXoTh00J5UM1n9GYjHDGcE5QXUXYk1VxfWBs+LZTH1HxYT28Mi4TyIsqOxHBN4dXweaE8mGa5nt4aPi6UF1F2JIazOs0CoZrrCcqjaJYIB4brCOVFlF3JcELHb/0J/vKnza0E5fuvuURPh4brC8pWlD2pmrc6futPvKjmVoLy/dW8KxwYvlhQtqLsSdW86vjNsusHf+5Hv+9WgvL907onzVHhiPKk+S4EZSvKnqQ0dPzWn9j11/8lWk8//IlbCcr3UPNWOKma71ZQtqLsSU/qN8uOv/avrTRrPRluJSjfJ82LTjpruI2gbEXZk974tX/qH/65XcHw5YJqDoVyL5LyUc1al84abi8oW1H2pVdlrdnVk2q+WFgZDoVyY2lHWah10nnDfempbEXZl16UjWbHD376w/+hmq8VVBoOBOU20jHlQum84Y6FshVlX1qrLC+ald6s/eAH/0U1XyowgtHTk7KSnpUbSPuqWelZzklnVPOtCGUryoFE2UrVrPRmrUvVfKVASSeUG0iqORDKgax03PBtCmUryvuaXUE1XyhQpI1KlGdJub70rByXhiNC2ZUODN++ULaivKfZ05Mf/b6vEyinJOUa0lHluDQcEYp0qJrvkaA8i/KuZleXfvgTX6Yn5culE8pRaTgivFHN91BQnkU5rdHR7OnJ8GWC8uXS1rAjKEclw6HwbPg+C8qzKKc1Opo9PRm+SqB8uWQ4FJS30sbwsILyLMoZjd680ZNqvkagfL1kOBSUjfTG8LiC8izKGY3evOoNPanmSwTlu5AMh8JJwwPrqTyLclLzRtfoiWouFIa1UM07gtF9F5LhUNgzTBuhPItySrOre5aeDJcIbwznBKP7TiTDMWGYDoTyLMoprbeORpeeFGljeFc4NJwRDN1XyZJ2DNPFQnkW5ajWraUdZS0xnNXTk0EMuuZJGM6IarrrSqcM0+WCshHlmKbbSM/KVvLDnzgjPBmedC9aGM6IQXcN6bRq9GZaJCgbUY5o3TnJcEp4Mjzp9qThjBh0H5ROq2b6nJ7KRpQDTXdWMhzV00o1dAeSgWA4IgbdYulAaaarCmUjynJJNccEqumOSi+GQ6Fad5F0aJi+TigbUZZLqjmi59Cdlp4MYTgiBt0J6aRh+mpBWYuyXFLNEaG8rwnDETHo9qSThum7E5S1KIu1oJodvfW0Vt7XhOGIGOjptGG6jaCsRVkoPRlWenqrvK8JwxExCAeG6eaCshZlmXRKuVAThiPCCFvDdEeCshZlmfTGsBaUC7UwTN+UoKxFeSuHE7qVxHAgKCelN4bpm9JTWYuyUDIcCsqrpksnDdO3paeyFmWhZDgUDE860hHD9A2LshFloWQ41NMRw/Q9EWUjykLJcER4Vs30/RPKWpQLNSudZDgqhul7K5S1KJdIu4bp4UTZiHJWoyNRrachDNPjibIR5Zj0qhrBMD2yUNaivJVeDEHJEYbpoYWyFuWtNLzqaW2YHlooa1HeSsM07QvKWpS30jBNWz1tlLUob6VhemjhmLIW5a00TN+g3nRyWCy8p7yI8lYapm9N2BqWCkeVo6K8lYbpWxO2hqO65oSwVd4X5a00TN+anio9GXb09GI4IRjdpaK8SM+G6ZsTtiodNZwQjO5SUZ6lV8P0jQmnFS2o5rhgdJeK8iy9GqZvRScdUXa1nqo5IYzuUlGeNRs9GaY7F94qZ7SeqjkhjO5SUbaajWCY7lxYK5dpPVVzQhjdpaK8aJ4Ehuk+BIYjgnK51tPf/3dOCMqlorxqVnoyTDcU9g2HQlmg9WQ4JSgXirKjoSfD9F0LJw2HQlmg9fQ3/5tTeioXirKjWQmG6bsQzigaeg5HhLJI+tt/7KRQLhRlV0NPw/QlYoQzyhE5HBHKIumHP3FSKBeKsqchDNMX6OlQeUcOO8JWWaD19HP/x0mhXCjKnoYwTF8gbJXLpePKAq0nw0mhXCjKvkYYpo/q6clwRCiLpaPKEk0wnBSUy0R5q4VqHljYGi4X9gxHhLJYWiufkEYwnBTKhaK8lRgeWNga3hVOGA5F+Ygsn5SeDCeFcqEoB5LhgYWt4ahwVHmRDIei3EZ6Us0pPcuFohxIhkcWVioZXoWjyjHJcKCnciOJak6KcqEoB5LhgYWVSmeVc5Jhq6etciuJak6KcqEoh9LwqHpaq3SoXCoNPb1VbqUF1ZwUymWiHErDIwkHirRWPiK9VVK5mRZUc1Iol4lyKFXzfRdOKp+WVsr9SFRzUiiXiXIoVfN91NMp5cqy3JPWUzUnhXKZKIeS4fskHFceRdNTNSeFcpkoh5LhGxfOKI+m6amak0K5TJRDyfAtCmeUB9b0VM1JoVwmyqFk+HaEc8okqVTNST3LZaLsSyUZ7l44pUz70pNqTotymSg70sogDPchMLzq6ahq6Kbj0pMf/b7TQrlIlB2JaoThpnq6wLCjm85I/N0/clooF4myI60MwnBL4bRqDnXTeYm/8d+dFspFouxIK4MwXE8wXCwcquakbrpA4hf/l9NCuUiUHenJ6KmaKwjPhouFjbKRDCd004USP/tTp4VykSg70ovh88LWsK9LhmNC2ZMMB7ppibQynBbKRaLsSgrJ8Hlha3gRXgxHRNmXDLu6abnEcFooF4lyRDJ8XngxuvTWcEQo+7KarW76mMRwWs9ykShHJMOn9PSs0r6ykYYjgrInq1nrpg9L/OVfcVqUi0Q5Ihk+IhyotFbeSMOhQHmj6abPSVRzWiiXiHJEMizX045C052Shldd2irT1eXP/V/VnBblIlGOScMZMRwTnhRJedJ0pyTDk7CvTNeXqOa0UC4R5Zg0HNNJT4YjQtnT6E5JR5XpKySqOS2US0Q5Jhl2hX3VHIqyr+lOS6/K9LUS1ZwWyiWiHJMMK+FQkQyHouxpdNN9SFRzWiiXiHJUequ8SoYDPcueppvuRKKa00K5RJSj0kY5JhneCJRdTTfdi0Q1p4VyiSgfkAxrPe0ou5puuheJak4L5RJRPiAdVXY13XQ/kmpO61kuEeUj0qtyXNNN9yOp5oxQLhDlIxLlvNZNdySp5oxQLhDlizTddEeSX/33zgjlAlG+RqOb7kjyK//ZGcGPfuxdUb5Go5vuSNLKGcEv/J53RfkaTTfdk+Tn/7czelLeFeVLNN10VxLDGT0p74ryJZpuuiuJ4Zy/88fKu6J8haab7ktiOKen8q4oX6HppvuSGM7p6Zd/13uifIGmm+5MopozelLeE+X6Gt10ZxLVnBOU90S5vqab7k2imnN+8c+U90S5vqab7k2imnN+/Q+U90S5vqab7k5SzTk9/ejH3hHl6ppuuj9JNWf1/IXf844oV9d00/1JqjmvZ3lHlGtruukOJdWc17O8I8q1Nd10h5Jq3hHlHVGurOmme5SqeU+Ud0S5rkY33aNUzTt6/vLvOi/KdTXddJdSNe/oqZwX5bqabrpLqZrzelLOi3JVjW66S6mad/zinynnRbmqppvuU6rmHb/+B8p5Ua6q6ab7lKp5R08/+rGzolxT0013KlXzjp5+4fecFeWamm66U6mad/SknBXlippuulepmvf81b9QzopyRU033afWUzXv+bX/oJwV5XqabrpTradq3tNTOSvK1TS66U61nqp5T0+//LvOiXI1TTfdq9ZTNe/pSTknytU03XSvWk/VvCso50S5lkY33avWUzXv6JJyTpRrabrpjqVqzgtPyjlRrqV10/1qPVVzVlDeE+VKmm66X1mpmjd6luZJT0/Ke6JcSdNN9ysrVbMjHCrvinIlrZvuWKKalZ5OKBeIMj2E9FbZSJSLRZkeQtpTNLrlokyPIZU9jW65KNODaroPiDI9qIZusSjTg2roFosyPaiGbrEo04Nq6BaLMj2qRrdYlOlRNXRLRZkeVUO3VJTpUTV0S0WZHlVDt1SU6WE1uqWiTA+roVsoyvSwGrqFokwPq6FbKMr0sBq6haJMD6uhWyjK9MAa3TJRpgfW6JaJMj2wRrdMlOmBNbplokwPrNEtE2V6ZI1ukSjTI2t0i0SZHlmjWyTK9Mga3SJRpkfW6BaJMj2yZqVbIMr00Bq6BaJMD62hWyDK9NAaugWiTA+toVsgyvTQmpXuclGmh9asdJeLMj22hu5yUabH1tBdLsr02Bq6y0WZHluz0l0syvTYmpXuYlGmx9asdBeLMj24hu5iUaYH19BdLMr04JqV7lJRpgfXrHSXijI9uGalu1SU6cE1K92lokwPr9FdKsr08Bq6C0WZHl5Dd6Eo08Nr6C4UZXp4Dd2FokwPr6G7UJRpala6i0SZpmalu0iUaWpWuotEmaZmpbtIlGlqVrqLRJmmJaJM0xJRpmmJKNO0RJRpWiLKNC0RZZqWiDJNS0SZpiX+P40WjWVy67CSAAAAAElFTkSuQmCC","metadata":{},"name":"Lab.png"}
          at Function.fromJSON (file:///wechaty/node_modules/file-box/src/file-box.ts:302:15)
          at messageSendFile (file:///wechaty/node_modules/wechaty-puppet-service/src/server/puppet-implementation.ts:751:37)
          at Object.messageSendFile (file:///wechaty/node_modules/wechaty-puppet-service/src/auth/auth-impl-token.ts:49:18)
          at handleUnary (/wechaty/node_modules/@grpc/grpc-js/src/server.ts:896:11)
          at processTicksAndRejections (node:internal/process/task_queues:96:5)")
         at Wechaty.Module.PuppetService.GrpcPuppet.MessageSendFile(String conversationId, FileBox file)
         at Wechaty.User.Contact.Say(FileBox fileBox)
         at RobotDemo.Server.Services.WechatService.SayImage(Object context, String to, String path) in /home/xdy/workspace/robotdemo/RobotDemo/Server/Services/WechatService.cs:line 162
```

**Comment by huan** [comment]
Thanks for reporting this problem!

This issue is related to:

- https://github.com/huan/file-box/issues/73

We have made some fixes and the latest version Wechaty should have updated with the fix.

Please try the `wechaty@1.11.8` or above version to see if it can fix your problem, and feel free to let us know whether it works or not.

**Comment by Jesn** [comment]
```
        private static string ImgToBase64String(string Imagefilename)
        {
            try
            {
                Bitmap bmp = new Bitmap(Imagefilename);

                MemoryStream ms = new MemoryStream();
                bmp.Save(ms, System.Drawing.Imaging.ImageFormat.Jpeg);
                byte[] arr = new byte[ms.Length];
                ms.Position = 0;
                ms.Read(arr, 0, (int)ms.Length);
                ms.Close();
                String strbaser64 = Convert.ToBase64String(arr);
                return strbaser64;
            }
            catch (Exception ex)
            {
                //LogHelper.Debug(ex);
                return "";
            }
        }


  private static async void WechatyMessageEventListenerAsync(Wechaty.User.Message message)
   {
            if (message.Text == "图片图片")
            {
                var base64 = ImgToBase64String(@"C:\xxx.png");
                var fileBox2 = FileBox.FromBase64(base64, "xx.png");
                await message.Say(fileBox2);
            }

        } 

```


目前先按照这样的来处理，至于卓桓所提的FileBox的版本问题，我后面看下是不是.net wechaty需要同步更新下
