### ISSUE TITLE
WECHATY_PUPPET_SERVICE_Endpoint应该填什么内容

### ISSUE THREAD

**Issue by tangjingtai** [wechaty/dotnet-wechaty#37]
WECHATY_PUPPET_SERVICE_Endpoint应该填什么内容

直接使用下载的代码运行报错

fail: Wechaty.Module.Puppet.WechatyPuppet[0]
      StartGrpcClient() exception,Grpc Retry Surplus Count 3
      System.UriFormatException: Invalid URI: The URI scheme is not valid.
         at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
         at System.Uri..ctor(String uriString)
         at Grpc.Net.Client.GrpcChannel.ForAddress(String address, GrpcChannelOptions channelOptions)
         at Wechaty.Module.PuppetService.GrpcPuppet.StartGrpcClient() in D:\Code\Git\dotnet-wechaty\src\modules\Wechaty.Module.PuppetService\GrpcPuppet.cs:line 146
         at Wechaty.Module.PuppetService.GrpcPuppet.StartGrpc() in D:\Code\Git\dotnet-wechaty\src\modules\Wechaty.Module.PuppetService\GrpcPuppet.cs:line 341

**Comment by Jesn** [comment]
eg:  `"WECHATY_PUPPET_SERVICE_ENDPOINT": "https://localhost:9002"`  
对应你wechaty gateway的地址，如果你wechaty使用的是老版未开启https则使用`http://`，如果开启了ssl的则使用`https://`
