### ISSUE TITLE
Grpc errors while concurrently connecting to 2 Wechat bots in 1 process or in 2 processes on 1 machine

### ISSUE THREAD

**Issue by lg810312** [wechaty/dotnet-wechaty#41]
I have successfuly developed an application connecting to a Wechat account. I am trying to concurrently connect to 2 Wechat bots. No matter connections are in 1 process or in 2 processes on 1 machine, the following grpc errors show up several times and one of bots stops working. It looks like dotnet-wechaty does not support doing so. Is it a matter of design or is it technically possible to do so?

fail: Wechaty.Module.Puppet.WechatyPuppet[0]
      StartGrpcClient() exception,Grpc Retry Surplus Count 3
      System.Exception: puppetClient had already inited
         at Wechaty.Module.PuppetService.GrpcPuppet.StartGrpcClient()
         at Wechaty.Module.PuppetService.GrpcPuppet.StartGrpc()

fail: Wechaty.Module.Puppet.WechatyPuppet[0]
      OnGrpcStreamEvent exception
      System.InvalidOperationException: must logout first before login again!
         at Wechaty.Module.Puppet.WechatyPuppet.set_SelfId(String value)
         at Wechaty.Module.PuppetService.GrpcPuppet.OnGrpcStreamEvent(EventResponse event)

**Comment by Jesn** [comment]
Only one can be connected. There is a risk of closing wechat accounts when connecting multiple
